build_from:
  aarch64: python:3.12-slim
  amd64: python:3.12-slim
  armhf: python:3.12-slim
  armv7: python:3.12-slim
  i386: python:3.12-slim

labels:
  org.opencontainers.image.title: KoServer
  org.opencontainers.image.description: Host for various services including KoBooks
  org.opencontainers.image.source: https://github.com/nefelodamon/KoServer
  org.opencontainers.image.licenses: MIT
