build_from:
  aarch64: docker.io/library/python:3.12-slim
  amd64: docker.io/library/python:3.12-slim
  armhf: docker.io/library/python:3.12-slim
  armv7: docker.io/library/python:3.12-slim
  i386: docker.io/library/python:3.12-slim

labels:
  org.opencontainers.image.title: KoServer
  org.opencontainers.image.description: Host for various services including KoBooks
  org.opencontainers.image.source: https://github.com/nefelodamon/KoServer
  org.opencontainers.image.licenses: MIT
