name: KoServer
version: "0.1.31"
slug: koserver
description: Host for various services including KoCharacters (KOReader character viewer)
url: https://github.com/nefelodamon/KoServer
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
boot: auto

panel_icon: mdi:bookshelf

ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web UI and API

options:
  api_key: ""
  ha_url: ""
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

schema:
  api_key: str
  ha_url: str
  ssl_certificate: str
  ssl_key: str

image: "ghcr.io/nefelodamon/koserver-{arch}"

map:
  - data:rw
  - share:rw
  - ssl:ro
